# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-08 19:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0002_auto_20171108_1942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(upload_to='faculty/Photos'),
        ),
    ]
