# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-09 07:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0003_auto_20171108_1952'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='profile_picture',
        ),
    ]
