# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-15 18:22
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('faculty', '0010_auto_20171115_1124'),
    ]

    operations = [
        migrations.CreateModel(
            name='publication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publication_name', models.CharField(max_length=200)),
                ('coll', models.CharField(max_length=200, null=True)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('publication_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
