# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-15 18:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0011_publication'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='other_info',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
