# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-15 21:28
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('faculty', '0012_publication_other_info'),
    ]

    operations = [
        migrations.CreateModel(
            name='course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_code', models.CharField(max_length=10)),
                ('course_name', models.CharField(max_length=200)),
                ('semester', models.CharField(choices=[('0', 'Even Semester'), ('1', 'Odd Semester')], max_length=10)),
                ('session_start', models.IntegerField(blank=True, null=True)),
                ('session_end', models.IntegerField(blank=True, null=True)),
                ('course_active', models.BooleanField(default=True)),
                ('course_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
