# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-16 15:45
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('faculty', '0019_auto_20171116_1418'),
    ]

    operations = [
        migrations.CreateModel(
            name='honor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('honor_name', models.CharField(max_length=10)),
                ('honor_from', models.CharField(max_length=200)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('honor_type', models.CharField(choices=[('Award', 'Award'), ('Achievement', 'Achievement'), ('Others', 'Others')], max_length=20)),
                ('honor_for', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
