# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-16 15:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0020_honor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='honor',
            name='honor_type',
            field=models.CharField(choices=[('0', 'Award'), ('1', 'Achievement'), ('2', 'Others')], max_length=20),
        ),
    ]
