# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-17 07:45
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('faculty', '0021_auto_20171116_1550'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255)),
                ('file', models.FileField(upload_to='faculty/docs')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('slides_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='honor',
            name='honor_from',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='honor',
            name='honor_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='honor',
            name='honor_type',
            field=models.CharField(choices=[('Award', 'Award'), ('Achievement', 'Achievement'), ('Others', 'Others')], max_length=20),
        ),
    ]
