# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-17 07:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0022_auto_20171117_0745'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='slides_by',
        ),
    ]
