# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-17 08:01
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('faculty', '0023_remove_photo_slides_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='slides_by',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
