# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-18 10:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0024_photo_slides_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='title',
            field=models.CharField(choices=[(b'0', b'Professor'), (b'1', b'Associate Professor'), (b'2', b'Assistant Professor'), (b'3', b'Visiting Faculty')], default=0, max_length=50),
            preserve_default=False,
        ),
    ]
